/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Sw9k4t1I8Ji
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { Fraunces } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

fraunces({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card, CardHeader, CardContent } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import Navbar from "./shared/Navbar"

export function AboutComponent() {
  return (
    <div className="flex min-h-screen flex-col">
      <Navbar />
      <main className="flex-1">
        <section className="bg-muted py-12 px-6">
          <div className="container mx-auto grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <h1 className="text-3xl font-bold mb-4">About Haitian Diaspora Connect</h1>
              <p className="text-muted-foreground mb-6">
                Haitian Diaspora Connect is a platform that aims to connect the global Haitian diaspora community. Our
                mission is to empower Haitians worldwide by providing resources, facilitating collaboration, and
                amplifying the voices and initiatives of the Haitian people.
              </p>
              <p className="text-muted-foreground mb-6">
                We believe that by harnessing the collective power of the Haitian diaspora, we can drive positive change
                and make a lasting impact on Haiti and its people. Through our crowdfunding platform, forum, and other
                initiatives, we strive to support Haitian-led projects, foster entrepreneurship, and build a stronger,
                more connected Haitian community.
              </p>
              <p className="text-muted-foreground mb-6">
                Join us in our mission to uplift and empower the Haitian diaspora. Together, we can create a brighter
                future for Haiti and its people.
              </p>
            </div>
            <div>
              <img
                src="/about-page.jpeg"
                alt="Haitian Diaspora"
                width={600}
                height={400}
                className="rounded-lg object-cover"
              />
            </div>
          </div>
        </section>
        <section className="py-12 px-6">
          <div className="container mx-auto">
            <h2 className="text-2xl font-bold mb-6">Our Team</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              <Card>
                <CardHeader>
                  <Avatar>
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                </CardHeader>
                <CardContent>
                  <div className="text-center">
                    <h3 className="text-lg font-medium">John Doe</h3>
                    <p className="text-muted-foreground">Co-Founder and CEO</p>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <Avatar>
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>ML</AvatarFallback>
                  </Avatar>
                </CardHeader>
                <CardContent>
                  <div className="text-center">
                    <h3 className="text-lg font-medium">Marie Laguerre</h3>
                    <p className="text-muted-foreground">Co-Founder and COO</p>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <Avatar>
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>SA</AvatarFallback>
                  </Avatar>
                </CardHeader>
                <CardContent>
                  <div className="text-center">
                    <h3 className="text-lg font-medium">Sophia Aurelien</h3>
                    <p className="text-muted-foreground">Head of Community Engagement</p>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 px-6">
          <div className="container mx-auto">
            <h2 className="text-2xl font-bold mb-6">Our Mission and Values</h2>
            <div className="max-w-2xl mx-auto">
              <div className="space-y-4">
                <div>
                  <h3 className="text-lg font-medium mb-2">Our Mission</h3>
                  <p>
                    Our mission is to empower the global Haitian diaspora community by providing resources, facilitating
                    collaboration, and amplifying the voices and initiatives of the Haitian people.
                  </p>
                </div>
                <div>
                  <h3 className="text-lg font-medium mb-2">Our Values</h3>
                  <ul className="list-disc pl-6 space-y-2">
                    <li>Empowerment: We believe in empowering Haitians worldwide to drive positive change.</li>
                    <li>Collaboration: We foster collaboration and community-building within the Haitian diaspora.</li>
                    <li>Integrity: We operate with honesty, transparency, and accountability.</li>
                    <li>Impact: We strive to create lasting, meaningful impact for Haiti and its people.</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-primary text-primary-foreground py-6 px-6">
        <div className="container mx-auto flex items-center justify-between">
          <p className="text-sm">&copy; 2023 Haitian Diaspora Connect</p>
          <div className="flex items-center space-x-4">
            <Link href="#" className="hover:underline" prefetch={false}>
              Privacy
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Terms
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Contact
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
