/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/zEX7WZYkdaS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { Fraunces } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

fraunces({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import Navbar from "./shared/Navbar"
import ShareIcon from "./shared/icons/ShareIcon"

export function CrowdFundingComponent() {
  return (
    <div className="flex min-h-screen flex-col">
      <Navbar />
      <main className="flex-1">
        <section className="bg-muted py-12 px-6">
          <div className="container mx-auto grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <h1 className="text-3xl font-bold mb-4">Crowdfunding for Haitian Initiatives</h1>
              <p className="text-muted-foreground mb-6">
                Support Haitian-led projects and initiatives through our crowdfunding platform. Contribute to causes
                that matter to you and the Haitian community.
              </p>
              <div className="flex space-x-4">
                <Button>Start a Campaign</Button>
                <Button variant="secondary">Explore Campaigns</Button>
              </div>
            </div>
            <div>
              <img
                src="/haitian-crowdfunding.jpeg"
                alt="Haitian Crowdfunding"
                width={600}
                height={400}
                className="rounded-lg object-cover"
              />
            </div>
          </div>
        </section>
        <section className="py-12 px-6">
          <div className="container mx-auto">
            <h2 className="text-2xl font-bold mb-6">Featured Campaigns</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              <Card>
                <CardHeader>
                  <CardTitle>Rebuilding Schools in Haiti</CardTitle>
                  <CardDescription>
                    Help us rebuild schools and provide quality education for Haitian children.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center space-x-2 mb-2">
                    <Avatar>
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <div>
                      <p className="font-medium">John Doe</p>
                      <p className="text-muted-foreground text-sm">2 days ago</p>
                    </div>
                  </div>
                  <p>
                    Many schools in Haiti were damaged or destroyed by natural disasters. Help us rebuild and provide a
                    safe learning environment for Haitian children.
                  </p>
                  <div className="mt-4">
                    <div className="bg-muted h-2 rounded-full">
                      <div className="bg-primary h-2 rounded-full w-3/4" />
                    </div>
                    <div className="flex justify-between text-sm text-muted-foreground mt-2">
                      <span>$15,000 raised of $20,000 goal</span>
                      <span>75% funded</span>
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <div className="flex items-center space-x-2">
                    <Button>Donate</Button>
                    <Button variant="ghost" size="icon">
                      <ShareIcon className="h-5 w-5" />
                    </Button>
                  </div>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Support Haitian Entrepreneurs</CardTitle>
                  <CardDescription>Help Haitian entrepreneurs start and grow their businesses.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center space-x-2 mb-2">
                    <Avatar>
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>ML</AvatarFallback>
                    </Avatar>
                    <div>
                      <p className="font-medium">Marie Laguerre</p>
                      <p className="text-muted-foreground text-sm">1 week ago</p>
                    </div>
                  </div>
                  <p>
                    Invest in Haitian-owned businesses and help them grow their impact in the community. Your
                    contribution can make a difference.
                  </p>
                  <div className="mt-4">
                    <div className="bg-muted h-2 rounded-full">
                      <div className="bg-primary h-2 rounded-full w-1/2" />
                    </div>
                    <div className="flex justify-between text-sm text-muted-foreground mt-2">
                      <span>$10,000 raised of $20,000 goal</span>
                      <span>50% funded</span>
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <div className="flex items-center space-x-2">
                    <Button>Donate</Button>
                    <Button variant="ghost" size="icon">
                      <ShareIcon className="h-5 w-5" />
                    </Button>
                  </div>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Empowering Haitian Women</CardTitle>
                  <CardDescription>Support initiatives that empower and uplift Haitian women.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center space-x-2 mb-2">
                    <Avatar>
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>SA</AvatarFallback>
                    </Avatar>
                    <div>
                      <p className="font-medium">Sophia Aurelien</p>
                      <p className="text-muted-foreground text-sm">3 days ago</p>
                    </div>
                  </div>
                  <p>
                    Haitian women are the backbone of our communities. Help us support initiatives that empower Haitian
                    women to lead, innovate, and create positive change.
                  </p>
                  <div className="mt-4">
                    <div className="bg-muted h-2 rounded-full">
                      <div className="bg-primary h-2 rounded-full w-2/3" />
                    </div>
                    <div className="flex justify-between text-sm text-muted-foreground mt-2">
                      <span>$12,000 raised of $18,000 goal</span>
                      <span>67% funded</span>
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <div className="flex items-center space-x-2">
                    <Button>Donate</Button>
                    <Button variant="ghost" size="icon">
                      <ShareIcon className="h-5 w-5" />
                    </Button>
                  </div>
                </CardFooter>
              </Card>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 px-6">
          <div className="container mx-auto">
            <h2 className="text-2xl font-bold mb-6">Start a New Campaign</h2>
            <div className="max-w-2xl mx-auto">
              <form className="space-y-4">
                <div>
                  <Label htmlFor="title">Campaign Title</Label>
                  <Input id="title" placeholder="Enter a title for your campaign" />
                </div>
                <div>
                  <Label htmlFor="description">Description</Label>
                  <Textarea id="description" placeholder="Provide a description of your campaign" rows={6} />
                </div>
                <div>
                  <Label htmlFor="goal">Funding Goal</Label>
                  <Input id="goal" type="number" placeholder="Enter your funding goal" />
                </div>
                <div className="flex justify-end">
                  <Button>Start Campaign</Button>
                </div>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-primary text-primary-foreground py-6 px-6">
        <div className="container mx-auto flex items-center justify-between">
          <p className="text-sm">&copy; 2023 Haitian Diaspora Connect</p>
          <div className="flex items-center space-x-4">
            <Link href="#" className="hover:underline" prefetch={false}>
              Privacy
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Terms
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Contact
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
