/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FnAla9lU7ud
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { Fraunces } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

fraunces({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { JSX, SVGProps } from "react"
import Navbar from "./shared/Navbar"
import ShareIcon from "./shared/icons/ShareIcon"
import { HeartIcon } from "@radix-ui/react-icons"
import MessageCircleIcon from "./shared/icons/MessageCircleIcon"

export function ForumComponent() {
  return (
    <div className="flex min-h-screen flex-col">
      <Navbar />
      <main className="flex-1">
        <section className="bg-muted py-12 px-6">
          <div className="container mx-auto grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <h1 className="text-3xl font-bold mb-4">Engage with the Haitian Community</h1>
              <p className="text-muted-foreground mb-6">
                Discuss important issues, share experiences, and connect with others in the Haitian diaspora.
              </p>
              <div className="flex space-x-4">
                <Button>Join the Forum</Button>
                <Button variant="secondary">Start a Fundraiser</Button>
              </div>
            </div>
            <div>
              <img
                src="/haitian-community-forum.jpeg"
                alt="Haitian Community Forum"
                width={600}
                height={400}
                className="rounded-lg object-cover"
              />
            </div>
          </div>
        </section>
        <section className="py-12 px-6">
          <div className="container mx-auto">
            <h2 className="text-2xl font-bold mb-6">Latest Forum Discussions</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              <Card>
                <CardHeader>
                  <CardTitle>Preserving Haitian Culture Abroad</CardTitle>
                  <CardDescription>
                    Discuss ways to maintain and celebrate Haitian culture in the diaspora.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center space-x-2 mb-2">
                    <Avatar>
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <div>
                      <p className="font-medium">John Doe</p>
                      <p className="text-muted-foreground text-sm">2 days ago</p>
                    </div>
                  </div>
                  <p>
                    As Haitians living abroad, it&apos;s important to find ways to preserve our rich cultural heritage. What
                    are some traditions, customs, or practices you&apos;ve been able to maintain in your community?
                  </p>
                </CardContent>
                <CardFooter>
                  <div className="flex items-center space-x-2">
                    <Button variant="ghost" size="icon">
                      <MessageCircleIcon className="h-5 w-5" />
                    </Button>
                    <Button variant="ghost" size="icon">
                      <HeartIcon className="h-5 w-5" />
                    </Button>
                    <Button variant="ghost" size="icon">
                      <ShareIcon className="h-5 w-5" />
                    </Button>
                  </div>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Improving Education in Haiti</CardTitle>
                  <CardDescription>
                    Discuss ways to support and enhance educational opportunities in Haiti.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center space-x-2 mb-2">
                    <Avatar>
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>ML</AvatarFallback>
                    </Avatar>
                    <div>
                      <p className="font-medium">Marie Laguerre</p>
                      <p className="text-muted-foreground text-sm">1 week ago</p>
                    </div>
                  </div>
                  <p>
                    Education is a crucial aspect of community development in Haiti. What initiatives or programs have
                    you seen or participated in that aim to improve access to quality education for Haitian children and
                    youth?
                  </p>
                </CardContent>
                <CardFooter>
                  <div className="flex items-center space-x-2">
                    <Button variant="ghost" size="icon">
                      <MessageCircleIcon className="h-5 w-5" />
                    </Button>
                    <Button variant="ghost" size="icon">
                      <HeartIcon className="h-5 w-5" />
                    </Button>
                    <Button variant="ghost" size="icon">
                      <ShareIcon className="h-5 w-5" />
                    </Button>
                  </div>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Empowering Haitian Women</CardTitle>
                  <CardDescription>
                    Discuss ways to support and empower Haitian women in the diaspora and in Haiti.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center space-x-2 mb-2">
                    <Avatar>
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>SA</AvatarFallback>
                    </Avatar>
                    <div>
                      <p className="font-medium">Sophia Aurelien</p>
                      <p className="text-muted-foreground text-sm">3 days ago</p>
                    </div>
                  </div>
                  <p>
                    Haitian women play a vital role in our communities, both locally and globally. How can we better
                    support and empower Haitian women to lead, innovate, and contribute to the betterment of our
                    communities?
                  </p>
                </CardContent>
                <CardFooter>
                  <div className="flex items-center space-x-2">
                    <Button variant="ghost" size="icon">
                      <MessageCircleIcon className="h-5 w-5" />
                    </Button>
                    <Button variant="ghost" size="icon">
                      <HeartIcon className="h-5 w-5" />
                    </Button>
                    <Button variant="ghost" size="icon">
                      <ShareIcon className="h-5 w-5" />
                    </Button>
                  </div>
                </CardFooter>
              </Card>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 px-6">
          <div className="container mx-auto">
            <h2 className="text-2xl font-bold mb-6">Start a New Discussion</h2>
            <div className="max-w-2xl mx-auto">
              <form className="space-y-4">
                <div>
                  <Label htmlFor="title">Title</Label>
                  <Input id="title" placeholder="Enter a title for your discussion" />
                </div>
                <div>
                  <Label htmlFor="content">Content</Label>
                  <Textarea id="content" placeholder="Write your discussion post here" rows={6} />
                </div>
                <div className="flex justify-end">
                  <Button>Post Discussion</Button>
                </div>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-primary text-primary-foreground py-6 px-6">
        <div className="container mx-auto flex items-center justify-between">
          <p className="text-sm">&copy; 2023 Haitian Diaspora Connect</p>
          <div className="flex items-center space-x-4">
            <Link href="#" className="hover:underline" prefetch={false}>
              Privacy
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Terms
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Contact
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}


